spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: feed-route
          uri: lb://feed
          predicates:
            - Path=/feed/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
        - id: songs-route
          uri: lb://songs
          predicates:
            - Path=/songs/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
        - id: songday-route
          uri: lb://songday
          predicates:
            - Path=/songday/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
        - id: feed-reactive-route
          uri: lb://feed-reactive
          predicates:
            - Path=/feed-reactive/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
        - id: songs-reactive-route
          uri: lb://songs-reactive
          predicates:
            - Path=/songs-reactive/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
        - id: songday-reactive-route
          uri: lb://songday-reactive
          predicates:
            - Path=/songday-reactive/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
            - name: CircuitBreaker
              args:
                  name: songs-find-by-id
                  registerHealthIndicator: true
                  ringBufferSizeInClosedState: 5
                  ringBufferSizeInHalfOpenState: 3
                  waitDurationInOpenState: 10s
                  failureRateThreashold: 5
                  recordExceptions:
                    - org.springframework.web.client.HttpServerErrorException
                    - java.io.IOException
                    - java.lang.IllegalStateException
                    - java.util.concurrent.TimeoutException
                    - org.springframework.web.client.ResourceAccessException
                    - java.lang.RuntimeException


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoint:
    gateway:
      enabled: true
    circuitbreakers:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG