management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    circuitbreakers:
      enabled: true
  health:
    circuitbreakers:
      enabled: true      
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: 'true'
    fetch-registry: 'true'
  instance:
    prefer-ip-address: 'true'
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
api:
  cached: 'false'
  cache:
    local: 'false'
spring:
  main:
    allow-bean-definition-overriding: 'true'
    web-application-type: reactive
  cloud:
    loadbalancer:
      ribbon:
        enabled: 'false'
  data:
    redis:
      url: redis://127.0.0.1:6379
    mongodb:
      database: songday
      uri: mongodb://localhost:27017
gateaway:
  api:
    address: http://localhost:8080/




resilience4j.circuitbreaker:
  instances:
    songs-find-by-id:
      registerHealthIndicator: true
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 7s
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.lang.IllegalStateException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
        - java.lang.RuntimeException
        - java.lang.Throwable    
